// Generated by `wit-bindgen` 0.32.0. DO NOT EDIT!
#include "imports.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wasmvision:platform/logging`

__attribute__((__import_module__("wasmvision:platform/logging"), __import_name__("log")))
extern void __wasm_import_wasmvision_platform_logging_log(uint8_t *, size_t);

__attribute__((__import_module__("wasmvision:platform/logging"), __import_name__("println")))
extern void __wasm_import_wasmvision_platform_logging_println(uint8_t *, size_t);

// Imported Functions from `wasmvision:platform/config`

__attribute__((__import_module__("wasmvision:platform/config"), __import_name__("get-config")))
extern void __wasm_import_wasmvision_platform_config_get_config(uint8_t *, size_t, uint8_t *);

// Imported Functions from `wasmvision:platform/key-value`

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[static]store.open")))
extern void __wasm_import_wasmvision_platform_key_value_static_store_open(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[method]store.get")))
extern void __wasm_import_wasmvision_platform_key_value_method_store_get(int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[method]store.set")))
extern void __wasm_import_wasmvision_platform_key_value_method_store_set(int32_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[method]store.delete")))
extern void __wasm_import_wasmvision_platform_key_value_method_store_delete(int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[method]store.exists")))
extern void __wasm_import_wasmvision_platform_key_value_method_store_exists(int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[method]store.get-keys")))
extern void __wasm_import_wasmvision_platform_key_value_method_store_get_keys(int32_t, uint8_t *);

// Imported Functions from `wasmvision:platform/http`

__attribute__((__import_module__("wasmvision:platform/http"), __import_name__("get")))
extern void __wasm_import_wasmvision_platform_http_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/http"), __import_name__("post")))
extern void __wasm_import_wasmvision_platform_http_post(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void wasmvision_platform_config_result_string_config_error_free(wasmvision_platform_config_result_string_config_error_t *ptr) {
  if (!ptr->is_err) {
    imports_string_free(&ptr->val.ok);
  } else {
  }
}

__attribute__((__import_module__("wasmvision:platform/key-value"), __import_name__("[resource-drop]store")))
extern void __wasm_import_wasmvision_platform_key_value_store_drop(int32_t handle);

void wasmvision_platform_key_value_store_drop_own(wasmvision_platform_key_value_own_store_t handle) {
  __wasm_import_wasmvision_platform_key_value_store_drop(handle.__handle);
}

wasmvision_platform_key_value_borrow_store_t wasmvision_platform_key_value_borrow_store(wasmvision_platform_key_value_own_store_t arg) {
  return (wasmvision_platform_key_value_borrow_store_t) { arg.__handle };
}

void wasmvision_platform_key_value_error_free(wasmvision_platform_key_value_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 3: {
      imports_string_free(&ptr->val.other);
      break;
    }
  }
}

void wasmvision_platform_key_value_result_own_store_error_free(wasmvision_platform_key_value_result_own_store_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasmvision_platform_key_value_error_free(&ptr->val.err);
  }
}

void imports_list_u8_free(imports_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void imports_option_list_u8_free(imports_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    imports_list_u8_free(&ptr->val);
  }
}

void wasmvision_platform_key_value_result_option_list_u8_error_free(wasmvision_platform_key_value_result_option_list_u8_error_t *ptr) {
  if (!ptr->is_err) {
    imports_option_list_u8_free(&ptr->val.ok);
  } else {
    wasmvision_platform_key_value_error_free(&ptr->val.err);
  }
}

void wasmvision_platform_key_value_result_void_error_free(wasmvision_platform_key_value_result_void_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasmvision_platform_key_value_error_free(&ptr->val.err);
  }
}

void wasmvision_platform_key_value_result_bool_error_free(wasmvision_platform_key_value_result_bool_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasmvision_platform_key_value_error_free(&ptr->val.err);
  }
}

void imports_list_string_free(imports_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    imports_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      imports_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void wasmvision_platform_key_value_result_list_string_error_free(wasmvision_platform_key_value_result_list_string_error_t *ptr) {
  if (!ptr->is_err) {
    imports_list_string_free(&ptr->val.ok);
  } else {
    wasmvision_platform_key_value_error_free(&ptr->val.err);
  }
}

void wasmvision_platform_http_result_list_u8_http_error_free(wasmvision_platform_http_result_list_u8_http_error_t *ptr) {
  if (!ptr->is_err) {
    imports_list_u8_free(&ptr->val.ok);
  } else {
  }
}

void imports_string_set(imports_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void imports_string_dup(imports_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void imports_string_free(imports_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void wasmvision_platform_logging_log(imports_string_t *msg) {
  __wasm_import_wasmvision_platform_logging_log((uint8_t *) (*msg).ptr, (*msg).len);
}

void wasmvision_platform_logging_println(imports_string_t *msg) {
  __wasm_import_wasmvision_platform_logging_println((uint8_t *) (*msg).ptr, (*msg).len);
}

bool wasmvision_platform_config_get_config(imports_string_t *key, imports_string_t *ret, wasmvision_platform_config_config_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_config_get_config((uint8_t *) (*key).ptr, (*key).len, ptr);
  wasmvision_platform_config_result_string_config_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_key_value_static_store_open(imports_string_t *label, wasmvision_platform_key_value_own_store_t *ret, wasmvision_platform_key_value_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_key_value_static_store_open((uint8_t *) (*label).ptr, (*label).len, ptr);
  wasmvision_platform_key_value_result_own_store_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasmvision_platform_key_value_own_store_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      wasmvision_platform_key_value_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          variant.val.other = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_key_value_method_store_get(wasmvision_platform_key_value_borrow_store_t self, imports_string_t *key, imports_option_list_u8_t *ret, wasmvision_platform_key_value_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_key_value_method_store_get((self).__handle, (uint8_t *) (*key).ptr, (*key).len, ptr);
  wasmvision_platform_key_value_result_option_list_u8_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      imports_option_list_u8_t option;
      switch ((int32_t) *((uint8_t*) (ptr + 4))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (imports_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.ok = option;
      break;
    }
    case 1: {
      result.is_err = true;
      wasmvision_platform_key_value_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          variant.val.other = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_key_value_method_store_set(wasmvision_platform_key_value_borrow_store_t self, imports_string_t *key, imports_list_u8_t *value, wasmvision_platform_key_value_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_key_value_method_store_set((self).__handle, (uint8_t *) (*key).ptr, (*key).len, (uint8_t *) (*value).ptr, (*value).len, ptr);
  wasmvision_platform_key_value_result_void_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasmvision_platform_key_value_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          variant.val.other = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_key_value_method_store_delete(wasmvision_platform_key_value_borrow_store_t self, imports_string_t *key, wasmvision_platform_key_value_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_key_value_method_store_delete((self).__handle, (uint8_t *) (*key).ptr, (*key).len, ptr);
  wasmvision_platform_key_value_result_void_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasmvision_platform_key_value_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          variant.val.other = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_key_value_method_store_exists(wasmvision_platform_key_value_borrow_store_t self, imports_string_t *key, bool *ret, wasmvision_platform_key_value_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_key_value_method_store_exists((self).__handle, (uint8_t *) (*key).ptr, (*key).len, ptr);
  wasmvision_platform_key_value_result_bool_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
    case 1: {
      result.is_err = true;
      wasmvision_platform_key_value_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          variant.val.other = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_key_value_method_store_get_keys(wasmvision_platform_key_value_borrow_store_t self, imports_list_string_t *ret, wasmvision_platform_key_value_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_key_value_method_store_get_keys((self).__handle, ptr);
  wasmvision_platform_key_value_result_list_string_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_list_string_t) { (imports_string_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      wasmvision_platform_key_value_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          variant.val.other = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_http_get(imports_string_t *url, imports_list_u8_t *ret, wasmvision_platform_http_http_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_http_get((uint8_t *) (*url).ptr, (*url).len, ptr);
  wasmvision_platform_http_result_list_u8_http_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_http_post(imports_string_t *url, imports_string_t *content_type, imports_list_u8_t *body, imports_list_u8_t *ret, wasmvision_platform_http_http_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_http_post((uint8_t *) (*url).ptr, (*url).len, (uint8_t *) (*content_type).ptr, (*content_type).len, (uint8_t *) (*body).ptr, (*body).len, ptr);
  wasmvision_platform_http_result_list_u8_http_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_imports(void);
void __component_type_object_force_link_imports_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_imports();
}
