// Generated by `wit-bindgen` 0.32.0. DO NOT EDIT!
#include "imports.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wasmvision:platform/time`

__attribute__((__import_module__("wasmvision:platform/time"), __import_name__("now")))
extern int64_t __wasm_import_wasmvision_platform_time_now(int32_t);

// Imported Functions from `wasmvision:platform/logging`

__attribute__((__import_module__("wasmvision:platform/logging"), __import_name__("log")))
extern void __wasm_import_wasmvision_platform_logging_log(uint8_t *, size_t);

__attribute__((__import_module__("wasmvision:platform/logging"), __import_name__("println")))
extern void __wasm_import_wasmvision_platform_logging_println(uint8_t *, size_t);

// Imported Functions from `wasmvision:platform/config`

__attribute__((__import_module__("wasmvision:platform/config"), __import_name__("get-config")))
extern void __wasm_import_wasmvision_platform_config_get_config(uint8_t *, size_t, uint8_t *);

// Imported Functions from `wasmvision:platform/http`

__attribute__((__import_module__("wasmvision:platform/http"), __import_name__("get")))
extern void __wasm_import_wasmvision_platform_http_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/http"), __import_name__("post")))
extern void __wasm_import_wasmvision_platform_http_post(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasmvision:platform/http"), __import_name__("post-image")))
extern void __wasm_import_wasmvision_platform_http_post_image(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void wasmvision_platform_config_result_string_config_error_free(wasmvision_platform_config_result_string_config_error_t *ptr) {
  if (!ptr->is_err) {
    imports_string_free(&ptr->val.ok);
  } else {
  }
}

void imports_list_u8_free(imports_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void wasmvision_platform_http_result_list_u8_http_error_free(wasmvision_platform_http_result_list_u8_http_error_t *ptr) {
  if (!ptr->is_err) {
    imports_list_u8_free(&ptr->val.ok);
  } else {
  }
}

void imports_string_set(imports_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void imports_string_dup(imports_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void imports_string_free(imports_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

uint64_t wasmvision_platform_time_now(uint32_t tz) {
  int64_t ret = __wasm_import_wasmvision_platform_time_now((int32_t) (tz));
  return (uint64_t) (ret);
}

void wasmvision_platform_logging_log(imports_string_t *msg) {
  __wasm_import_wasmvision_platform_logging_log((uint8_t *) (*msg).ptr, (*msg).len);
}

void wasmvision_platform_logging_println(imports_string_t *msg) {
  __wasm_import_wasmvision_platform_logging_println((uint8_t *) (*msg).ptr, (*msg).len);
}

bool wasmvision_platform_config_get_config(imports_string_t *key, imports_string_t *ret, wasmvision_platform_config_config_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_config_get_config((uint8_t *) (*key).ptr, (*key).len, ptr);
  wasmvision_platform_config_result_string_config_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_http_get(imports_string_t *url, imports_list_u8_t *ret, wasmvision_platform_http_http_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_http_get((uint8_t *) (*url).ptr, (*url).len, ptr);
  wasmvision_platform_http_result_list_u8_http_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_http_post(imports_string_t *url, imports_string_t *content_type, imports_list_u8_t *body, imports_list_u8_t *ret, wasmvision_platform_http_http_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_http_post((uint8_t *) (*url).ptr, (*url).len, (uint8_t *) (*content_type).ptr, (*content_type).len, (uint8_t *) (*body).ptr, (*body).len, ptr);
  wasmvision_platform_http_result_list_u8_http_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasmvision_platform_http_post_image(imports_string_t *url, imports_string_t *content_type, imports_list_u8_t *request_template, imports_string_t *response_item, uint32_t mat, imports_list_u8_t *ret, wasmvision_platform_http_http_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasmvision_platform_http_post_image((uint8_t *) (*url).ptr, (*url).len, (uint8_t *) (*content_type).ptr, (*content_type).len, (uint8_t *) (*request_template).ptr, (*request_template).len, (uint8_t *) (*response_item).ptr, (*response_item).len, (int32_t) (mat), ptr);
  wasmvision_platform_http_result_list_u8_http_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (imports_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_imports(void);
void __component_type_object_force_link_imports_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_imports();
}
