interface http {
    /// Get the content at the specified URL.
    /// Returns either the content or an error.
    get: func(url: string) -> result<list<u8>, http-error>;

    /// Post the content to the specified URL.
    /// Returns either the response content or an error.
    post: func(url: string, content-type: string, body: list<u8>) -> result<list<u8>, http-error>;

    // HTTP errors returned by the runtime.
    enum http-error {
        success,
        destination-not-allowed,
        invalid-url,
        request-error,
        runtime-error,
        too-many-requests,
    }
}