package wasmvision:platform;
/// wasmvision is a WebAssembly guest module interface for host functions provided by the wasmVision runtime.
///
world imports {
    import key-value;
    import http;
}
