package wasmvision:platform;
/// wasmvision is a WebAssembly guest module interface for host functions provided by the wasmVision runtime.
///
world imports {
    import time;
    import logging;
    import config;
    import http;
}
